# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(585, 430)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(585, 430))
        MainWindow.setMaximumSize(QtCore.QSize(585, 430))
        MainWindow.setWindowTitle("Youtube Downloader 7v")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("YtExtraFiles/YtDownloader.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(200, 200, 200);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(586, 405))
        self.centralwidget.setMaximumSize(QtCore.QSize(560, 405))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background-color: #181818;")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mainWidget = QtWidgets.QWidget(self.centralwidget)
        self.mainWidget.setStyleSheet("background-color: #181818;")
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout.setContentsMargins(11, 0, 11, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_widget = QtWidgets.QWidget(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_widget.sizePolicy().hasHeightForWidth())
        self.search_widget.setSizePolicy(sizePolicy)
        self.search_widget.setMinimumSize(QtCore.QSize(0, 36))
        self.search_widget.setStyleSheet("background-color: #181818;")
        self.search_widget.setObjectName("search_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.search_widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search_input = QtWidgets.QLineEdit(self.search_widget)
        self.search_input.setToolTip("Coloque um link de um video ou pesquise videos do youtube")
        self.search_input.setStyleSheet("QToolTip {\n"
"color: white;\n"
"}\n"
" * {\n"
"background-color: #202020;\n"
"color: rgb(200, 200, 200);\n"
"border: 1px solid #272727;\n"
"}\n"
"*:hover {\n"
"border: 1px solid #353535;\n"
"}\n"
"*:focus {\n"
"border: 1px solid #404040;\n"
"}\n"
"\n"
"")
        self.search_input.setPlaceholderText("URL OU PESQUISAR")
        self.search_input.setObjectName("search_input")
        self.horizontalLayout_2.addWidget(self.search_input)
        self.search_spinbox = QtWidgets.QSpinBox(self.search_widget)
        self.search_spinbox.setToolTip("Quantidade de videos a serem pesquisados\n"
"")
        self.search_spinbox.setStyleSheet("QToolTip {\n"
"color: white;\n"
"}\n"
" * {\n"
"background-color: #202020;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid #272727;\n"
"}\n"
"*:hover {\n"
"border: 1px solid #353535;\n"
"}\n"
"*:focus {\n"
"border: 1px solid #404040;\n"
"}")
        self.search_spinbox.setMinimum(5)
        self.search_spinbox.setMaximum(40)
        self.search_spinbox.setSingleStep(5)
        self.search_spinbox.setObjectName("search_spinbox")
        self.horizontalLayout_2.addWidget(self.search_spinbox)
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.search_btn = QtWidgets.QPushButton(self.search_widget)
        self.search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_btn.setStyleSheet("QToolTip {\n"
"color: white;\n"
"}\n"
" * {\n"
"background-color: #202020;\n"
"color: rgb(200, 200, 200);\n"
"}\n"
"")
        self.search_btn.setText("Procurar")
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_2.addWidget(self.search_btn)
        self.verticalLayout.addWidget(self.search_widget)
        self.download_widget = QtWidgets.QWidget(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_widget.sizePolicy().hasHeightForWidth())
        self.download_widget.setSizePolicy(sizePolicy)
        self.download_widget.setMinimumSize(QtCore.QSize(0, 50))
        self.download_widget.setStyleSheet("background-color: #181818;")
        self.download_widget.setObjectName("download_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.download_widget)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchBox = QtWidgets.QComboBox(self.download_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBox.sizePolicy().hasHeightForWidth())
        self.searchBox.setSizePolicy(sizePolicy)
        self.searchBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchBox.setStyleSheet("QToolTip {\n"
"color: white;\n"
"}\n"
" * {\n"
"background-color: #202020;\n"
"color: rgb(200, 200, 200);\n"
"border: 1px solid #272727;\n"
"}\n"
"*:hover {\n"
"border: 1px solid #353535;\n"
"}\n"
"*:focus {\n"
"border: 1px solid #404040;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"outline: none;\n"
"}\n"
"")
        self.searchBox.setDuplicatesEnabled(True)
        self.searchBox.setObjectName("searchBox")
        self.horizontalLayout_3.addWidget(self.searchBox)
        self.downloadBtn = QtWidgets.QPushButton(self.download_widget)
        self.downloadBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.downloadBtn.setStyleSheet("QToolTip {\n"
"color: white;\n"
"}\n"
" * {\n"
"background-color: #202020;\n"
"color: rgb(200, 200, 200);\n"
"}\n"
"")
        self.downloadBtn.setText("Baixar")
        self.downloadBtn.setObjectName("downloadBtn")
        self.horizontalLayout_3.addWidget(self.downloadBtn)
        self.verticalLayout.addWidget(self.download_widget)
        self.download_table = QtWidgets.QTableWidget(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_table.sizePolicy().hasHeightForWidth())
        self.download_table.setSizePolicy(sizePolicy)
        self.download_table.setMinimumSize(QtCore.QSize(0, 220))
        self.download_table.setStyleSheet("\n"
"* {\n"
"background-color: #202020;\n"
"color: rgb(200, 200, 200);\n"
"border: 1px solid #272727;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"background-color: #202020;\n"
"color: rgb(200, 200, 200);\n"
"\n"
"}")
        self.download_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.download_table.setProperty("showDropIndicator", False)
        self.download_table.setCornerButtonEnabled(False)
        self.download_table.setObjectName("download_table")
        self.download_table.setColumnCount(5)
        self.download_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Título")
        self.download_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Tamanho")
        self.download_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Velocidade")
        self.download_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Baixado")
        self.download_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Status")
        self.download_table.setHorizontalHeaderItem(4, item)
        self.download_table.horizontalHeader().setDefaultSectionSize(112)
        self.download_table.horizontalHeader().setMinimumSectionSize(0)
        self.download_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.download_table)
        self.config_widget = QtWidgets.QWidget(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_widget.sizePolicy().hasHeightForWidth())
        self.config_widget.setSizePolicy(sizePolicy)
        self.config_widget.setMinimumSize(QtCore.QSize(0, 57))
        self.config_widget.setStyleSheet("background-color: #181818;")
        self.config_widget.setObjectName("config_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.config_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qualities_box = QtWidgets.QComboBox(self.config_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qualities_box.sizePolicy().hasHeightForWidth())
        self.qualities_box.setSizePolicy(sizePolicy)
        self.qualities_box.setMinimumSize(QtCore.QSize(160, 0))
        self.qualities_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qualities_box.setToolTip("Opções de download")
        self.qualities_box.setStyleSheet("QToolTip {\n"
"color: white;\n"
"}\n"
" * {\n"
"background-color: #202020;\n"
"color: rgb(200, 200, 200);\n"
"border: 1px solid #272727;\n"
"}\n"
"*:hover {\n"
"border: 1px solid #353535;\n"
"}\n"
"*:focus {\n"
"border: 1px solid #404040;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"outline: none;\n"
"}\n"
"")
        self.qualities_box.setCurrentText("Apenas o áudio")
        self.qualities_box.setObjectName("qualities_box")
        self.qualities_box.addItem("")
        self.qualities_box.setItemText(0, "Melhor qualidade possível")
        self.qualities_box.addItem("")
        self.qualities_box.setItemText(1, "1080p")
        self.qualities_box.addItem("")
        self.qualities_box.setItemText(2, "720p")
        self.qualities_box.addItem("")
        self.qualities_box.setItemText(3, "480p")
        self.qualities_box.addItem("")
        self.qualities_box.setItemText(4, "360p")
        self.qualities_box.addItem("")
        self.qualities_box.setItemText(5, "Pior qualidade possível")
        self.qualities_box.addItem("")
        self.qualities_box.setItemText(6, "Apenas o áudio")
        self.horizontalLayout.addWidget(self.qualities_box)
        spacerItem1 = QtWidgets.QSpacerItem(63, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.folder_btn = QtWidgets.QPushButton(self.config_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folder_btn.sizePolicy().hasHeightForWidth())
        self.folder_btn.setSizePolicy(sizePolicy)
        self.folder_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.folder_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.folder_btn.setToolTip("Selecione a pasta que o arquivo será baixado")
        self.folder_btn.setStyleSheet("QToolTip {\n"
"color: black;\n"
"}\n"
" * {\n"
"background-color: rgb(103, 103, 103);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.folder_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("YtExtraFiles/folder.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.folder_btn.setIcon(icon1)
        self.folder_btn.setIconSize(QtCore.QSize(30, 30))
        self.folder_btn.setFlat(True)
        self.folder_btn.setObjectName("folder_btn")
        self.horizontalLayout.addWidget(self.folder_btn)
        self.folders_box = QtWidgets.QComboBox(self.config_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folders_box.sizePolicy().hasHeightForWidth())
        self.folders_box.setSizePolicy(sizePolicy)
        self.folders_box.setMinimumSize(QtCore.QSize(240, 20))
        self.folders_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.folders_box.setToolTip("Locais para salvar o arquivo")
        self.folders_box.setStyleSheet("QToolTip {\n"
"color: white;\n"
"}\n"
" * {\n"
"background-color: #202020;\n"
"color: rgb(200, 200, 200);\n"
"border: 1px solid #272727;\n"
"}\n"
"*:hover {\n"
"border: 1px solid #353535;\n"
"}\n"
"*:focus {\n"
"border: 1px solid #404040;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"outline: none;\n"
"}")
        self.folders_box.setCurrentText("")
        self.folders_box.setObjectName("folders_box")
        self.horizontalLayout.addWidget(self.folders_box)
        self.verticalLayout.addWidget(self.config_widget)
        self.horizontalLayout_4.addWidget(self.mainWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 24))
        self.menubar.setStyleSheet("* {\n"
"background-color: #202020;\n"
"color: rgb(200, 200, 200);\n"
"border: 1px solid #272727;\n"
"}\n"
"\n"
"*:hover {\n"
"background-color: #303030;\n"
"color: rgb(220, 220, 220);\n"
"}")
        self.menubar.setObjectName("menubar")
        self.menuConfig = QtWidgets.QMenu(self.menubar)
        self.menuConfig.setToolTip("Ficar na frente")
        self.menuConfig.setStyleSheet("* {\n"
"background-color: #202020;\n"
"color: rgb(200, 200, 200);\n"
"}\n"
"*:hover {\n"
"background-color: #303030;\n"
"color: rgb(220, 220, 220);\n"
"}\n"
"*:focus {\n"
"background-color: #303030;\n"
"color: rgb(220, 220, 220);}")
        self.menuConfig.setTitle("Configurações")
        self.menuConfig.setToolTipsVisible(True)
        self.menuConfig.setObjectName("menuConfig")
        MainWindow.setMenuBar(self.menubar)
        self.toggle_window_btn = QtWidgets.QAction(MainWindow)
        self.toggle_window_btn.setText("Ficar na frente")
        self.toggle_window_btn.setIconText("Ficar na frente")
        self.toggle_window_btn.setToolTip("Ficar na frente")
        self.toggle_window_btn.setObjectName("toggle_window_btn")
        self.reset_folders_btn = QtWidgets.QAction(MainWindow)
        self.reset_folders_btn.setText("Resetar pastas")
        self.reset_folders_btn.setIconText("Resetar pastas")
        self.reset_folders_btn.setToolTip("Resetar pastas")
        self.reset_folders_btn.setObjectName("reset_folders_btn")
        self.reset_suggestions_btn = QtWidgets.QAction(MainWindow)
        self.reset_suggestions_btn.setObjectName("reset_suggestions_btn")
        self.menuConfig.addAction(self.toggle_window_btn)
        self.menuConfig.addAction(self.reset_folders_btn)
        self.menuConfig.addAction(self.reset_suggestions_btn)
        self.menubar.addAction(self.menuConfig.menuAction())

        self.retranslateUi(MainWindow)
        self.qualities_box.setCurrentIndex(6)
        self.folders_box.setCurrentIndex(-1)
        self.search_input.returnPressed.connect(self.search_btn.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.reset_suggestions_btn.setText(_translate("MainWindow", "Resetar sugestões"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
